ADD:제품상세페이지 불러오기 기능 구현
wecode-bootcamp-korea/26-1st-WASH-Korea-backend pull request #7
Opened 2021-11-08 03:59 UTC by fore0919

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
-제품상세페이지 불러오기 기능 구현 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 제품 상세페이지 불러오기 기능 
- productdetail View.py작성
- GET 메소드 사용
- 이미지 불러오기 = 역참조
- 
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- ```
def get(self, request, product_id):
        try:
            product = Product.objects.get(product_id=id)
```
![image](https://user-images.githubusercontent.com/91520365/140681911-57cbd21f-68ff-4db8-9a5d-56da533ae58f.png)
product_id를 장고에서 인식을 못하는 것 같아서  
 ```
def get(self, request, id):
        try:
            product = Product.objects.get(id=id)
```
id=id 로 변경해 주었더니 500 오류 해결되었습니다.

```
'product_image' : [
                {
                'id'  : product_image.id,
                'url' : product_image.url,
            }for product_image in product.product_image_set.all()]   
```
![image](https://user-images.githubusercontent.com/91520365/140682127-d8a1379b-a646-4e47-b745-760c5498787b.png)
product_image 부분이 소문자 클래스 명인줄 몰라서 계속 오류가 발생했었는데
언더바를 삭제해 주었더니 해결되었습니다 ! 

<br />

2021-11-08 12:31 UTC, Kang-kyunghun requested changes

2021-11-08 12:31 UTC, Kang-kyunghun commented on users/views.py
> +                return JsonResponse({'message':'ALREADY_EXISTS_USERNAME'}, status=409)
```suggestion
            
            if User.objects.filter(user_name=user_name).exists():
                return JsonResponse({'message':'ALREADY_EXISTS_USERNAME'}, status=409)
```

2021-11-08 12:31 UTC, Kang-kyunghun commented on users/views.py
> +                return JsonResponse({'message':'ALREADY_EXISTS_USERNAME'}, status=409)
if들 사이에 공백 하나 추가해 주세요.

2021-11-08 12:31 UTC, Kang-kyunghun commented on products/views.py
> +                return JsonResponse({'message' : '상품 상세정보가 존재하지 않습니다.'}, status=404)
에러 메시지 영어로 바꿔주세요.

2021-11-09 01:52 UTC, fore0919 commented on products/views.py
> +                return JsonResponse({'message' : '상품 상세정보가 존재하지 않습니다.'}, status=404)
리뷰사항 반영하여 수정 완료했습니다 !

2021-11-09 02:50 UTC, Kang-kyunghun commented
LGTM 👍

2021-11-09 02:50 UTC, merged