[권은경]Review기능 구현
wecode-bootcamp-korea/26-1st-WASH-Korea-backend pull request #8
Opened 2021-11-10 01:23 UTC by fore0919

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [x] 리팩토링
- [x] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 제품리뷰 - 불러오기/작성/수정/삭제 기능 구현 
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 리뷰기능구현 Views.py 작성
- [GET]불러오기
- [POST]작성
- [DELETE]삭제
- [POST]수정

2. 리뷰기능 구현을 위한 추가 작업 
- urls.py 작성 
- models.py 수정 (필드명 혼동 우려가 있어 user_id, product_id에서 _id를 삭제해 주었습니다.
)<img width="1096" alt="스크린샷 2021-11-10 오전 8 49 35" src="https://user-images.githubusercontent.com/91520365/141030806-178f4725-e888-4936-b27a-d4606000a7a6.png">
- 팀원들과 데이터베이스 공유를 위해 review CSV 파일 추가 
- wash/urls.py 에 리뷰 url추가 

3. 로그인 데코레이터 오류 관련 수정
- core/utils.py 수정 (INVALID_TOKEN오류)
<img width="1014" alt="스크린샷 2021-11-10 오전 8 46 14" src="https://user-images.githubusercontent.com/91520365/141030783-b90e1c76-20b7-4e96-b5f5-dc215bbe701b.png">

- users/views.py 엑세스 토큰 수정  
<img width="1100" alt="스크린샷 2021-11-10 오전 8 52 05" src="https://user-images.githubusercontent.com/91520365/141030915-c2bf1527-e61d-47d9-ad12-22f563d98421.png">

4. TEST 완료 

- 리뷰 작성
<img width="836" alt="스크린샷 2021-11-10 오전 9 04 07" src="https://user-images.githubusercontent.com/91520365/141031799-ed0af92c-ebd8-4a4f-a852-c7bc225fc387.png">

-리뷰 작성 에러코드 확인
<img width="827" alt="스크린샷 2021-11-10 오전 9 11 46" src="https://user-images.githubusercontent.com/91520365/141032201-9aa875a4-2876-43d7-9084-5bba832b3010.png">
<img width="830" alt="스크린샷 2021-11-10 오전 9 12 40" src="https://user-images.githubusercontent.com/91520365/141032205-46be8e76-e49d-4ff9-b970-8b5dd0d1a34a.png">

- 리뷰 불러오기
<img width="796" alt="스크린샷 2021-11-10 오전 9 06 42" src="https://user-images.githubusercontent.com/91520365/141031830-50feaad4-65ab-479d-8dbc-50c6c7448af3.png">

-리뷰 삭제 
<img width="827" alt="스크린샷 2021-11-10 오전 9 08 23" src="https://user-images.githubusercontent.com/91520365/141031958-50638fde-ab53-4e6f-891c-bb73677f1992.png">

-리뷰 수정

<img width="869" alt="스크린샷 2021-11-10 오전 9 09 18" src="https://user-images.githubusercontent.com/91520365/141032021-e8bb74c4-70fa-499c-883f-6ad06a5eea91.png">

-리뷰수정 반영 확인
<img width="865" alt="스크린샷 2021-11-10 오전 9 09 34" src="https://user-images.githubusercontent.com/91520365/141032060-7db069bc-1da5-40fc-9888-e93f58c32f40.png">

-리뷰수정 에러코드 확인
<img width="861" alt="스크린샷 2021-11-10 오전 9 13 13" src="https://user-images.githubusercontent.com/91520365/141032262-bf33ecf4-6f57-4305-8ba3-67d138005317.png">

5. 기타 수정사항
 
- users/views.py 들여쓰기 수정 
- 엑세스 토큰 변경 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- GET메소드와 POST메소드를 조금 더  이해할 수 있었습니다. 
- POST 메소드 이용시 data.get()으로 데이터를 가져오면 모든필드를 전달하지 않아도 일부만 수 
  정/업데이트가 가능하다는 것을 알게 되었습니다. 
- 포스트맨을 이용해 TEST 하는법을 알게 되었습니다.
<br />

## :: 기타 질문 및 특이 사항
- updated_at 필드에 표시되는 시간 서식이 알아보기가 힘든데 혹시 settings.py에서 수정해야 하는지 궁금합니다.
- ReviewUpdateView에서  data.get()로 데이터를 가져왔더니 KET ERROR가 반환되지 않습니다. 어떻게 해야하는지 궁금합니다
<img width="850" alt="스크린샷 2021-11-10 오전 9 08 44" src="https://user-images.githubusercontent.com/91520365/141032331-93308252-3abc-484a-a88a-f0fee23015c1.png">
(KEY 값이 content가 아닌 conten이 들어와도 SUCCESS가 반환됩니다 )
.

2021-11-10 14:35 UTC, fore0919 commented
멘토님 리뷰주신 내용 반영해서 수정커밋 했습니다 .
wash/settings.py  - TIME_ZONE = 'Asia/Seoul' 로 수정해 주었습니다

2021-11-11 01:13 UTC, Kang-kyunghun requested changes

2021-11-11 01:13 UTC, Kang-kyunghun commented on reviews/urls.py
> +    path('',ReviewView.as_view()),
```suggestion
    path('',ReviewListView.as_view()),
    path('',ReviewView.as_view()),
```

2021-11-11 01:13 UTC, Kang-kyunghun commented on reviews/views.py
> +            return JsonResponse({'message' : 'SUCCESS'}, status = 201)
```suggestion
            return JsonResponse({'message' : 'SUCCESS'}, status = 200)
```
201 에러 코드는 생성 할 때만 사용하면 좋을 것 같아요~

2021-11-11 01:18 UTC, Gyubs commented
에러사항 발견해서 댓글로 남겨둡니다 !

에러내용 : POST url/reviews 로 통신 시 reviews에는 POST 메소드는 없다는 에러 발생

생각한 이유 : 클래스 명을 하나로 합치는 과정에서 POST 에는 product_id 값이 필요한데 review_id 값만 패스파라미터로 입력 됨

생각한 해결방안 :  POST를 위한 클래스명을 분리 해서 url 변경이 필수적이라고 생각했습니다

1. app : reviews / urls.py 에서 해당 클래스에 해당하는 url 설정 (ex. reviews/product/<int:product_id>)
2. app : wash / urls.py 에서 해당 클래스에 해당하는 url 설정 (ex. 여기서는 마땅한 이름이 안떠오릅니다../<int:product_id>) 
3. app : products / urls.py 에서 해당 클래스에 해당하는 url 설정 (ex. products/reviews/<int:product_id>)

2021-11-11 05:09 UTC, Kang-kyunghun commented
고생 많으셨습니다~~!!
LGTM~~!! 👍

2021-11-11 05:09 UTC, merged

2021-11-11 05:11 UTC, fore0919 commented
21.11.11

1. 리뷰 반영 완료
2. POST 오류 위치 변경해서 해결
3. 규빈님이 작업한 내용 merge main후 conflict 해결완료
4. ReviewListView GET List Comprehension 적용
5. 리뷰 models.py 이미지 필드 blank=True -> null=True 값으로 변경

감사합니다 고생많으셨습니다 ~!!!!😚👍👍